############################################
##                                        ##
##   filename: 2bar_1display.yaml         ##
##   description: Specific configuration  ##
##   for the 2 BAR's, 1 Display setup     ##
##                                        ##
############################################

packages: 
    base: !include base.yaml

mcp23008:
  - id: 'base_J1'
    i2c_id: buttons
    address: 0x21
  - id: 'base_J2'
    i2c_id: buttons
    address: 0x22
  - id: 'base_J3'
    i2c_id: buttons
    address: 0x23

binary_sensor:
  ############################
  ### Buttons Main Display ###
  ############################
  - platform: gpio
    id: 'base_j1_btn_left'
    name: "Display button Left"
    pin: 
      mcp23xxx: base_J1
      number: 6
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    id: 'base_j1_btn_right'
    name: "Display button Right"
    pin: 
      mcp23xxx: base_J1
      number: 2
      mode: INPUT_PULLUP
      inverted: true
      
  ############################
  ### Buttons BAR module 1 ###
  ############################
  - platform: gpio
    id: 'base_j2_btn_left'
    name: "BAR 1 button Left"
    pin: 
      mcp23xxx: base_J2
      number: 6
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    id: 'base_j2_btn_right'
    name: "BAR 1 button Right"
    pin: 
      mcp23xxx: base_J2
      number: 2
      mode: INPUT_PULLUP
      inverted: true

  ############################
  ### Buttons BAR module 2 ###
  ############################
  - platform: gpio
    id: 'base_j3_btn_left'
    name: "BAR 2 button Left"
    pin: 
      mcp23xxx: base_J3
      number: 6
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    id: 'base_j3_btn_right'
    name: "BAR 2 button Right"
    pin: 
      mcp23xxx: base_J3
      number: 2
      mode: INPUT_PULLUP
      inverted: true

light:
  - id: !extend neopixels
    num_leds: 9
  ##############################
  ### RGB LED's BAR module 1 ###
  ##############################
  - platform: partition
    name: "BAR 1 Left RGB Front"
    id: bar_1_left_rgb_front
    segments:
      - id: neopixels
        from: 0
        to: 0
  - platform: partition
    name: "BAR 1 Left RGB Back"
    id: bar_1_left_rgb_back
    segments:
      - id: neopixels
        from: 1
        to: 1
  - platform: partition
    name: "BAR 1 Right RGB Front"
    id: bar_1_right_rgb_front
    segments:
      - id: neopixels
        from: 2
        to: 2
  - platform: partition
    name: "BAR 1 Right RGB Back"
    id: bar_1_right_rgb_back
    segments:
      - id: neopixels
        from: 3
        to: 3
  ##############################
  ### RGB LED's BAR module 2 ###
  ##############################
  - platform: partition
    name: "BAR 2 Left RGB Front"
    id: bar_2_left_rgb_front
    segments:
      - id: neopixels
        from: 4
        to: 4
  - platform: partition
    name: "BAR 2 Left RGB Back"
    id: bar_2_left_rgb_back
    segments:
      - id: neopixels
        from: 5
        to: 5
  - platform: partition
    name: "BAR 2 Right RGB Front"
    id: bar_2_right_rgb_front
    segments:
      - id: neopixels
        from: 6
        to: 6
  - platform: partition
    name: "BAR 2 Right RGB Back"
    id: bar_2_right_rgb_back
    segments:
      - id: neopixels
        from: 7
        to: 7

display:
  ####################
  ### Main Display ###
  ####################
  - id: display_j1_main
    platform: ili9xxx
    model: ili9341
    color_order: rgb
    invert_colors: false
    dc_pin: 
      number: GPIO37
      allow_other_uses: true
    cs_pin: 
      mcp23xxx: base_J1
      number: 5
      mode:
        output: true
      inverted: false
    update_interval: 200ms
    show_test_card: false
    dimensions: 
      height: 240
      width: 320
    rotation: 180
  ####################
  ### BAR module 1 ###
  ####################
  - id: display_j2_Left
    platform: ili9xxx
    model: ST7735
    color_order: bgr
    dc_pin: 
      number: GPIO37
      allow_other_uses: true
    cs_pin: 
      mcp23xxx: base_J2
      number: 5
      mode:
        output: true
      inverted: false
    invert_colors: false
    show_test_card: false
    dimensions: 
      height: 160
      width: 80
      offset_width: 24
    rotation: 270
    update_interval: 1s
  - id: display_j2_Right
    platform: ili9xxx
    model: ST7735
    color_order: bgr
    dc_pin:
      number: GPIO37
      allow_other_uses: true
    cs_pin: 
      mcp23xxx: base_J2
      number: 1
      mode:
        output: true
      inverted: false
    invert_colors: false
    show_test_card: false
    dimensions: 
      height: 160
      width: 80
      offset_width: 24
    rotation: 90
    update_interval: 1s
  ####################
  ### BAR module 2 ###
  ####################
  - id: display_j3_Left
    platform: ili9xxx
    model: ST7735
    color_order: bgr
    dc_pin: 
      number: GPIO37
      allow_other_uses: true
    cs_pin: 
      mcp23xxx: base_J3
      number: 5
      mode:
        output: true
      inverted: false
    invert_colors: false
    show_test_card: false
    dimensions: 
      height: 160
      width: 80
      offset_width: 24
    rotation: 270
    update_interval: 1s
  - id: display_j3_Right
    platform: ili9xxx
    model: ST7735
    color_order: bgr
    dc_pin:
      number: GPIO37
      allow_other_uses: true
    cs_pin: 
      mcp23xxx: base_J3
      number: 1
      mode:
        output: true
      inverted: false
    invert_colors: false
    show_test_card: false
    dimensions: 
      height: 160
      width: 80
      offset_width: 24
    rotation: 90
    update_interval: 1s
