###########################################
##                                       ##
##   filename: base.yaml                 ##
##   description: contains configuration ##
##   that will be the same for all the   ##
##   possible configurations             ##
##                                       ##
###########################################

esp32:
  flash_size: 16MB

i2c:
  - id: temperature_sensor
    sda: GPIO1
    scl: GPIO2
  - id: buttons
    sda: GPIO47
    scl: GPIO48
    frequency: 400khz

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35

output:
  - platform: ledc
    pin: GPIO3
    id: display_main_backlight_pwm
    inverted: True
    max_power: 1.0
    frequency: 500Hz
  - platform: ledc
    pin: GPIO46
    id: displays_mini_backlight_pwm
    inverted: True
    max_power: 0.6
    frequency: 500Hz

sensor:
  - platform: sts3x
    id: inside_temperature
    i2c_id: temperature_sensor
    name: "Temperature"
    address: 0x4A
    update_interval: 10s

light:
  - platform: neopixelbus
    id: neopixels
    type: RGB
    variant: WS2812
    pin: GPIO4
    num_leds: 17
  - platform: monochromatic
    output: display_main_backlight_pwm
    gamma_correct : 2.2
    name: "Main Display Backlight"
    id: display_main_backlight
    restore_mode: ALWAYS_ON
  - platform: monochromatic
    output: displays_mini_backlight_pwm
    gamma_correct : 2.2
    name: "Mini Display Backlight"
    id: displays_mini_backlight
    restore_mode: ALWAYS_ON
    
time:
  - platform: homeassistant
    id: datetime
